### ISSUE TITLE
Peer Node Handling Errors

### ISSUE THREAD

**Issue by CoinDev** [sarchar/pyspv#4]
```
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 619, in make_connection
    self.socket.connect(self.peer_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 565, in run
    self.step()
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 594, in step
    if self.make_connection():
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 626, in make_connection
    self.manager.peer_is_bad(self.peer_address)
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 336, in peer_is_bad
    self.delete_peer_address(peer_address)
  File "/usr/local/lib/python3.3/dist-packages/pyspv/network.py", line 225, in delete_peer_address
    self.peer_addresses[peer_address]['index'] = old['index']
KeyError: ('87.105.8.146', 18333)
```

**Comment by Jacob2J** [comment]
Hello, I'm also getting the same issue. Anyone found a solution?
Could this be because the peer address is changing?

**Comment by ALittleStudent** [comment]
> Hello, I'm also getting the same issue. Anyone found a solution?
> Could this be because the peer address is changing?

Hello,i try to fix the bug.
i find in the pyspv/network.py may line 217,
`old = self.peer_addresses.pop(peer_address)`
i change it to `old = self.peer_addresses[peer_address]`
bug there are new errors
`
Traceback (most recent call last):
  File "/home/liu/test/my/pyspv-master/pyspv/network.py", line 323, in check_for_new_peers
    self.start_new_peer()
  File "/home/liu/test/my/pyspv-master/pyspv/network.py", line 345, in start_new_peer
    raise OutOfPeers()
pyspv.network.OutOfPeers
`

**Comment by Fl0x23** [comment]
> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 980, in cmd_version
    self.peer_last_block = struct.unpack("<L", payload)[0]
struct.error: unpack requires a buffer of 4 bytes
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 565, in run
    self.step()
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 602, in step
    self.handle_incoming_data()
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 673, in handle_incoming_data
    self.handle_command(command, payload)
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 705, in handle_command
    cmd(payload)
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 984, in cmd_version
    self.manager.peer_is_bad(self.peer_address)
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 336, in peer_is_bad
    self.delete_peer_address(peer_address)
  File "/usr/local/lib/python3.6/dist-packages/pyspv/network.py", line 225, in delete_peer_address
    self.peer_addresses[peer_address]['index'] = old['index']
KeyError: ('120.27.215.53', 18333)
